services:
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    volumes:
      - pipelines:/app/pipelines
    restart: always
    environment:
      - PIPELINES_API_KEY=0p3n-w3bu!
    ports:
      - "9099:9099"
    networks:
      - easypanel

volumes:
  pipelines: {}

networks:
  easypanel:
    external: true
